name: CI/CD Docker PHP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -f docker/apache-php.dockerfile -t php-app .

      - name: Run docker-compose
        run: docker-compose up -d --build

      - name: Check PHP files
        run: docker exec $(docker ps -qf "ancestor=php-app") php -v
