name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Show PHP version
        run: php -v

      - name: Run PHP Syntax Check
        run: php check_syntax.php

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug secrets
        run: |
          echo "DOCKER_USERNAME length: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_USERNAME.length || 0 }}"
          echo "DOCKER_PASSWORD length: ${{ secrets.DOCKER_PASSWORD && secrets.DOCKER_PASSWORD.length || 0 }}"

      - name: Build Docker Image
        run: docker build -t nightdoom/productivity-app .

      - name: Push Docker Image
        run: docker push nightdoom/productivity-app
