name: Docker Compose CI

on:
  push:
    branches:
      - main  # sesuaikan dengan branch kamu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx (optional, tapi direkomendasikan)
      uses: docker/setup-buildx-action@v2

    - name: Build and run containers
      run: |
        docker compose up -d --build

    - name: Check running containers
      run: docker ps

    # Optional: test koneksi database, atau cek aplikasi respons
    # - name: Wait for DB to be ready (example)
    #   run: |
    #     until docker exec $(docker ps -q -f name=db) mysqladmin ping -h "127.0.0.1" --silent; do
    #       echo "Waiting for database connection..."
    #       sleep 3
    #     done
