name: Docker Compose CI and Publish

on:
  push:
    branches:
      - main  # sesuaikan dengan branch kamu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t nightdoom/my-image:latest .
        # ganti nightdoom/my-image sesuai nama image kamu

    - name: Push Docker image to Docker Hub
      run: |
        docker push nightdoom/my-image:latest

    - name: Build and run containers (optional)
      run: |
        docker compose up -d --build

    - name: Check running containers
      run: docker ps
